version: '3'

services:
    api: 
        build:
            context: .
            dockerfile: Dockerfile 
        volumes:
            - .:/usr/src/app
        ports:
            - 8070:8070
        working_dir: /usr/src/app